version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: madecomfyau/node-aws:10

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-yarn-cache-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-cache-

      - run: yarn install
      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-cache-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  tag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: git config user.name $CIRCLE_USERNAME
      - run: git config user.email "eng@madecomfy.com.au"
      - run: npm version patch -m "Bumped up to version %s"
      - run: git push origin master && git push --tags

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Bump up version
          command: npm --no-git-tag-version version ${CIRCLE_TAG:1}
      - run:
          name: Update master
          command:
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9].*/
      - tag:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
